# -*- coding: utf-8 -*-
"""Faker_Vendas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cE5lC16BP7211CsdAz1TcbIvrQ0uxTMM
"""

!pip install faker

import pandas as pd
from faker import Faker
import random
import numpy as np

# Inicializa o Faker
fake = Faker()

# Função para gerar dados para 4 tabelas

def gerar_dados():
    # Tabela de Clientes
    clientes = []
    for i in range(100):
        clientes.append({
            'ID_Cliente': i + 1,
            'Nome_Cliente': fake.name(),
            'Segmento': random.choice(['Retail', 'Corporate', 'Government']),
            'Região': random.choice(['Norte', 'Sul', 'Leste', 'Oeste'])
        })
    df_clientes = pd.DataFrame(clientes)

    # Tabela de Produtos
    produtos = []
    for i in range(50):
        produtos.append({
            'ID_Produto': i + 1,
            'Nome_Produto': fake.word().capitalize(),
            'Categoria': random.choice(['Tecnologia', 'Alimentos', 'Vestuário', 'Saúde']),
            'Preço': round(random.uniform(10, 1000), 2)
        })
    df_produtos = pd.DataFrame(produtos)

    # Tabela de Metas
    metas = []
    for i in range(20):
        metas.append({
            'ID_Meta': i + 1,
            'Vendedor': fake.name(),
            'Região': random.choice(['Norte', 'Sul', 'Leste', 'Oeste']),
            'Meta_Mensal': round(random.uniform(5000, 50000), 2)
        })
    df_metas = pd.DataFrame(metas)

    # Tabela de Vendas
    vendas = []
    for i in range(500):
        vendas.append({
            'ID_Venda': i + 1,
            'Data_Venda': fake.date_this_year(),
            'ID_Cliente': random.choice(df_clientes['ID_Cliente']),
            'ID_Produto': random.choice(df_produtos['ID_Produto']),
            'Quantidade': random.randint(1, 10),
            'Valor_Total': round(random.uniform(20, 1000), 2),
            'Região': random.choice(['Norte', 'Sul', 'Leste', 'Oeste'])
        })
    df_vendas = pd.DataFrame(vendas)

    return df_vendas, df_clientes, df_produtos, df_metas

# Gerando os dados
df_vendas, df_clientes, df_produtos, df_metas = gerar_dados()

# Salvando os dados em arquivos CSV
df_vendas.to_csv('vendas.csv', index=False)
df_clientes.to_csv('clientes.csv', index=False)
df_produtos.to_csv('produtos.csv', index=False)
df_metas.to_csv('metas.csv', index=False)

print("Dados gerados e salvos com sucesso!")